import React, { useEffect, useState } from 'react'
import NavBar from '../Navbar/NavBar'
import axios from 'axios';
import video from '../Video/4_trimmed_0.mp4'
import ReactPlayer from 'react-player'

function Ai() {

  const [savedData, setSavedData] = useState({});

    const fetchSavedData = async () => {
        try {
          const response = await axios.get('http://127.0.0.1:5000/api/model_data');
          setSavedData(response.data);
        } catch (error) {
          console.error('Error fetching saved data:', error);
        }
      };
      useEffect(() => {
        fetchSavedData();
      }, []);

  return (
    <div>
      <NavBar/>
      <h1>Work in Progress</h1>
            <div className="Video">
              <br/>
      
      </div>
      <div>
            <h3>Saved Model data generated by Traffic Analysis Model</h3>
      {Object.keys(savedData).length > 0 ? (
        <table border="1" cellPadding="10" style={{ marginTop: '20px', borderCollapse: 'collapse' }}>
          <thead>
            <tr>
              <th>model</th>
              <th>Time (Seconds)</th>
            </tr>
          </thead>
          <tbody>
            {Object.entries(savedData).map(([Time, Data], index) => (
              <tr key={index}>
                <td>{Time}</td>
                <td>{Data}</td>
              </tr>
            ))}
          </tbody>
        </table>
      ) : (
        <p>No Model Data Available.</p>
      )}
            </div>
    </div>
  )
}

export default Ai
